name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"       # refreshes once a day
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_languages: yes
          plugin_lines: yes
          plugin_habits: yes